version: '3.8'

services:
  # PostgreSQL database for Temporal
  postgres:
    image: postgres:14-alpine
    container_name: temporal-postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      # Persist database data between restarts
      - temporal_postgres_data:/var/lib/postgresql/data
    networks:
      - temporal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal server
  temporal:
    image: temporalio/auto-setup:1.23.1
    container_name: temporal-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - "7233:7233"
    networks:
      - temporal-network
    volumes:
      # Use the built-in development dynamic config
      - ./temporal-dynamic-config:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap

  # Temporal Web UI
  temporal-ui:
    image: temporalio/ui:2.25.0
    container_name: temporal-web-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    ports:
      - "8080:8080"
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge
    name: temporal-dev-network

volumes:
  temporal_postgres_data:
    name: temporal-postgres-data